name: srcs3build

on: pull_request

env:
  SBT: ./sbt
  JDK: 1.8
  REPO_SLUG: ${{ github.repository }}
  ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.10]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK }}
      - name: Setup Git Actor
        run: git config github.actor slamdata-bot
      - name: Decode testCredentials
        run: base64 -d testCredentials.json.b64 > testCredentials.json
      - name: Run datasourceAssemblePlugin
        run: ./sbt ++${{ matrix.scala }} datasourceAssemblePlugin
      - name: Compile and test
        run: $SBT ++${{ matrix.scala }} ci
      - name: Upload target
        uses: actions/upload-artifact@v1
        with:
          name: target
          path: target

  publishandtag:
    name: Publish and Tag
    if: github.event_name != 'pull_request' && (contains(github.head_ref, 'backport/v.*') || contains(github.head_ref, 'master'))
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Download target artifacts
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Setup Git Actor
        run: git config github.actor slamdata-bot
      - name: Create scripts dir
        run: mkdir ./scripts
      - name: Run transferPublishAndTagResources
        run: ./scripts/publishAndTag 'slamdata/quasar-datasource-s3'
      - name: Bump Downstream
        run: |
          bumpInDownstream() { echo $1 > slamdata-s3-version; }
          export -f bumpInDownstream
          ./scripts/bumpDependentProject slamdata slamx bumpInDownstream

  automerge:
    name: Auto Merge
    if: github.event_name == 'pull_request' && contains(github.head_ref, 'version-bump')
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Download target artifacts
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Setup Git Actor
        run: git config github.actor slamdata-bot
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK }}
      - name: Install common resources
        run:  $SBT transferCommonResources
      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Set env vars
        run: |
          echo ::set-env name=VERSIONS::$(git diff HEAD^1 | grep -e '^[-+][0-9]' | sed 's/^[+\-]//' | sed 's/\.[0-9]*$//' | uniq | wc -l)
          echo ::set-env name=CLONE_DIR::$(mktemp -d "/tmp/slamdata-bump.XXXXXXXX")
          echo ::set-env name=IS_REVISION_LABEL::${{ contains(github.event.pull_request.labels.*.name, 'revision') }}
          echo ::set-env name=PR_NUMBER::$(echo "$GITHUB_REF" | cut -d'/' -f3)
      - name: Run automerge
        run: ./scripts/core/checkAndAutoMerge
